# Generated by Django 2.2.4 on 2019-08-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillPer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillper',
            name='time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
