# Generated by Django 2.2.4 on 2019-08-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkillPer', '0002_skillper_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelPer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=10)),
                ('priority', models.IntegerField(max_length=2)),
            ],
            options={
                'db_table': 'level_person',
            },
        ),
        migrations.AlterField(
            model_name='skillper',
            name='skill_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillPer.LevelPer'),
        ),
    ]
