# Generated by Django 2.2.4 on 2019-08-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=3)),
                ('skill_name', models.CharField(max_length=20)),
                ('skill_level', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'skill_person',
            },
        ),
    ]
