# Generated by Django 2.2.4 on 2019-08-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkillPer', '0003_auto_20190816_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillper',
            name='skill_level',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='LevelPer',
        ),
    ]
